### ISSUE TITLE
Error when running on iOS

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-react-native#25]
Error info:

> warning: the transform cache was reset.
> Loading dependency graph, done.
> error: bundling failed: Error: Unable to resolve module `react-native` from `../BlockstackSDK/index.js`: react-native could not be found within the project.
> If you are sure the module exists, try these steps:
>  1. Clear watchman watches: watchman watch-del-all
>  2. Delete node_modules: rm -rf node_modules and run yarn install
>  3. Reset Metro's cache: yarn start --reset-cache
>  4. Remove the cache: rm -rf /tmp/metro-*
>     at ModuleResolver.resolveDependency (/Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
>     at ResolutionRequest.resolveDependency (/Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
>     at DependencyGraph.resolveDependency (/Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
>     at Object.resolve (/Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/lib/transformHelpers.js:267:42)
>     at dependencies.map.result (/Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31)
>     at Array.map (<anonymous>)
>     at resolveDependencies (/Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
>     at /Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (/Users/admin/Documents/blockstack-react-native/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
>  BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 5.5% (4/17), failed.
>

**Comment by ntheile** [comment]
i am also having a lot of trouble running this on the latest react-native 0.61.4.  any hints or ideas on why?

**Comment by shreyasthiagaraj** [comment]
@ntheile Are you getting this error? My theory is that it was caused by the recent release of iOS 13.2, which just came out like 2 weeks ago.

**Comment by ntheile** [comment]
yeah, i get a similar error.  even after i cleared all the caches and ran [react-native-clean-project ](https://www.npmjs.com/package/react-native-clean-project)

**Comment by ntheile** [comment]
i wonder if it has to do with this "CLI has been extracted from core react-native as a part of "Lean Core" effort. Please read this [blog](https://github.com/facebook/react-native/issues/23313) post for more details." [https://github.com/react-native-community/cli](https://github.com/react-native-community/cli)

**Comment by ntheile** [comment]
@shreyasthiagaraj any updates or ideas on this one?

**Comment by brocodedude** [comment]
Any updates? It's been 2 years.
